import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const DEFAULT_CATEGORIES = [
  { slug: 'RIGID_TRUCK', name: 'Rigid Truck', description: 'Rigid body truck for general freight', icon: '🚛' },
  { slug: 'ARTICULATED_TRUCK', name: 'Articulated Truck', description: 'Tractor + trailer combination', icon: '🚜' },
  { slug: 'TANKER', name: 'Tanker', description: 'Liquid/gas transport tanker', icon: '🛢' },
  { slug: 'REFRIGERATED', name: 'Refrigerated', description: 'Temperature-controlled reefer truck', icon: '❄️' },
  { slug: 'FLATBED', name: 'Flatbed', description: 'Open flatbed for oversized cargo', icon: '📏' },
  { slug: 'BOX_TRUCK', name: 'Box Truck', description: 'Enclosed box body truck', icon: '📦' },
  { slug: 'PICKUP', name: 'Pickup', description: 'Light commercial pickup truck', icon: '🛻' },
  { slug: 'VAN', name: 'Van', description: 'Delivery van for last-mile', icon: '🚐' },
  { slug: 'TRAILER', name: 'Trailer', description: 'Standalone trailer unit', icon: '🔗' },
  { slug: 'LOWBED', name: 'Lowbed', description: 'Heavy equipment hauler / lowloader', icon: '⚙️' },
  { slug: 'CURTAIN_SIDER', name: 'Curtain Sider', description: 'Side-curtain truck for easy loading', icon: '🏗' },
  { slug: 'CAR_CARRIER', name: 'Car Carrier', description: 'Multi-level vehicle transporter', icon: '🚗' },
  { slug: 'TIPPER', name: 'Tipper/Dump Truck', description: 'Hydraulic tipping body for bulk materials', icon: '🪨' },
  { slug: 'CEMENT_MIXER', name: 'Cement Mixer', description: 'Rotating drum concrete mixer', icon: '🏗' },
  { slug: 'CRANE_TRUCK', name: 'Crane Truck', description: 'Truck-mounted crane for heavy lifts', icon: '🏗' },
];

const SAMPLE_VEHICLES = [
  {
    fleetNumber: 'VH-001',
    make: 'Mercedes-Benz',
    model: 'Actros 2645',
    year: 2023,
    color: 'White',
    vehicleType: 'ARTICULATED_TRUCK',
    licensePlate: 'أ ب ت 1234',
    chassisNumber: 'WDB9634031L654321',
    engineNumber: 'OM471-A6-001',
    istimaraNumber: 'IST-2023-98765',
    istimaraExpiry: new Date('2025-06-15'),
    registrationCity: 'Riyadh',
    capacity: 26,
    grossVehicleWeight: 45000,
    netWeight: 19000,
    numberOfAxles: 6,
    lengthMeters: 16.5,
    widthMeters: 2.55,
    heightMeters: 4.0,
    fuelType: 'DIESEL',
    tankCapacityLiters: 400,
    engineCapacityCC: 12800,
    transmissionType: 'Automatic',
    horsePower: 450,
    tgaOperationCardNumber: 'TGA-OC-2023-0012',
    tgaOperationCardExpiry: new Date('2025-04-20'),
    waselTrackerId: 'WASEL-SAT-001',
    waselConnected: true,
    speedLimiterInstalled: true,
    speedLimitKmh: 90,
    insuranceProvider: 'Tawuniya',
    insurancePolicyNo: 'TWN-2024-FL-0012',
    insuranceType: 'COMPREHENSIVE',
    insuranceStartDate: new Date('2024-01-01'),
    insuranceExpiryDate: new Date('2025-01-01'),
    lastMvpiDate: new Date('2024-09-01'),
    nextMvpiDate: new Date('2025-09-01'),
    mvpiStation: 'Fahes Riyadh - Al Sulay',
    mvpiResult: 'PASS',
    currentOdometerKm: 87500,
    notes: 'Primary long-haul unit. Riyadh ↔ Jeddah route.',
  },
  {
    fleetNumber: 'VH-002',
    make: 'Isuzu',
    model: 'FVR 34Q',
    year: 2022,
    color: 'White',
    vehicleType: 'REFRIGERATED',
    licensePlate: 'ح د و 5678',
    chassisNumber: 'JALFVR34QN0012345',
    engineNumber: '6HK1-TCN-002',
    istimaraNumber: 'IST-2022-54321',
    istimaraExpiry: new Date('2025-03-10'),
    registrationCity: 'Jeddah',
    capacity: 8,
    grossVehicleWeight: 16000,
    netWeight: 8000,
    numberOfAxles: 2,
    lengthMeters: 9.5,
    widthMeters: 2.4,
    heightMeters: 3.8,
    fuelType: 'DIESEL',
    tankCapacityLiters: 200,
    engineCapacityCC: 7790,
    transmissionType: 'Manual',
    horsePower: 240,
    tgaOperationCardNumber: 'TGA-OC-2022-0089',
    tgaOperationCardExpiry: new Date('2025-08-15'),
    waselTrackerId: 'WASEL-SAT-002',
    waselConnected: true,
    speedLimiterInstalled: true,
    speedLimitKmh: 100,
    insuranceProvider: 'Al Rajhi Takaful',
    insurancePolicyNo: 'ART-2024-FL-0034',
    insuranceType: 'COMPREHENSIVE',
    insuranceStartDate: new Date('2024-03-01'),
    insuranceExpiryDate: new Date('2025-03-01'),
    lastMvpiDate: new Date('2024-07-15'),
    nextMvpiDate: new Date('2025-07-15'),
    mvpiStation: 'Fahes Jeddah - Al Hamdaniyah',
    mvpiResult: 'PASS',
    currentOdometerKm: 62300,
    notes: 'Cold chain unit. Perishable goods within Jeddah metro.',
  },
  {
    fleetNumber: 'VH-003',
    make: 'Hino',
    model: '500 Series 1726',
    year: 2024,
    color: 'Silver',
    vehicleType: 'BOX_TRUCK',
    licensePlate: 'ر س ش 9012',
    chassisNumber: 'JTFR1726XN0067890',
    istimaraNumber: 'IST-2024-11223',
    istimaraExpiry: new Date('2026-01-20'),
    registrationCity: 'Dammam',
    capacity: 10,
    grossVehicleWeight: 17000,
    netWeight: 7000,
    numberOfAxles: 2,
    fuelType: 'DIESEL',
    tankCapacityLiters: 200,
    transmissionType: 'Manual',
    horsePower: 260,
    waselTrackerId: 'WASEL-SAT-003',
    waselConnected: true,
    speedLimiterInstalled: true,
    speedLimitKmh: 100,
    insuranceProvider: 'Bupa Arabia',
    insurancePolicyNo: 'BUPA-2024-FL-0056',
    insuranceType: 'AGAINST_OTHERS',
    insuranceStartDate: new Date('2024-06-01'),
    insuranceExpiryDate: new Date('2025-06-01'),
    lastMvpiDate: new Date('2024-06-01'),
    nextMvpiDate: new Date('2025-06-01'),
    mvpiStation: 'Fahes Dammam',
    mvpiResult: 'PASS',
    currentOdometerKm: 23100,
    notes: 'New unit — Eastern Province distribution.',
  },
  {
    fleetNumber: 'VH-004',
    make: 'MAN',
    model: 'TGS 40.480',
    year: 2021,
    color: 'Blue',
    vehicleType: 'TANKER',
    licensePlate: 'ع ف ق 3456',
    chassisNumber: 'WMAN40480YN098765',
    istimaraNumber: 'IST-2021-77889',
    istimaraExpiry: new Date('2025-02-28'),
    registrationCity: 'Riyadh',
    capacity: 35,
    grossVehicleWeight: 40000,
    netWeight: 15000,
    numberOfAxles: 4,
    lengthMeters: 12.0,
    widthMeters: 2.55,
    heightMeters: 3.5,
    fuelType: 'DIESEL',
    tankCapacityLiters: 500,
    engineCapacityCC: 12419,
    transmissionType: 'Automatic',
    horsePower: 480,
    tgaOperationCardNumber: 'TGA-OC-2021-0045',
    tgaOperationCardExpiry: new Date('2025-01-10'),
    waselTrackerId: 'WASEL-SAT-004',
    waselConnected: true,
    speedLimiterInstalled: true,
    speedLimitKmh: 80,
    insuranceProvider: 'Tawuniya',
    insurancePolicyNo: 'TWN-2024-FL-0078',
    insuranceType: 'COMPREHENSIVE',
    insuranceStartDate: new Date('2024-01-01'),
    insuranceExpiryDate: new Date('2024-12-31'),
    lastMvpiDate: new Date('2024-04-20'),
    nextMvpiDate: new Date('2025-04-20'),
    mvpiStation: 'Fahes Riyadh - North',
    mvpiResult: 'PASS',
    currentOdometerKm: 198000,
    status: 'ACTIVE',
    notes: 'Fuel tanker. HAZMAT certified. Saudi Aramco contract.',
  },
  {
    fleetNumber: 'VH-005',
    make: 'Toyota',
    model: 'Hilux 2.4D',
    year: 2024,
    color: 'White',
    vehicleType: 'PICKUP',
    licensePlate: 'ك ل م 7890',
    chassisNumber: 'JTFDU5DH9P0543210',
    istimaraNumber: 'IST-2024-55667',
    istimaraExpiry: new Date('2026-08-01'),
    registrationCity: 'Riyadh',
    capacity: 1,
    grossVehicleWeight: 3200,
    netWeight: 2100,
    numberOfAxles: 2,
    fuelType: 'DIESEL',
    tankCapacityLiters: 80,
    transmissionType: 'Automatic',
    horsePower: 150,
    waselConnected: false,
    speedLimiterInstalled: false,
    insuranceProvider: 'Walaa Insurance',
    insurancePolicyNo: 'WAL-2024-PU-0091',
    insuranceType: 'THIRD_PARTY',
    insuranceStartDate: new Date('2024-08-01'),
    insuranceExpiryDate: new Date('2025-08-01'),
    currentOdometerKm: 8500,
    notes: 'Support vehicle — site surveys and supervisor transport.',
  },
  {
    fleetNumber: 'VH-006',
    make: 'Volvo',
    model: 'FH16 750',
    year: 2020,
    color: 'Red',
    vehicleType: 'LOWBED',
    licensePlate: 'ن ه و 2345',
    chassisNumber: 'YV2RTG0A5LB112233',
    istimaraNumber: 'IST-2020-33445',
    istimaraExpiry: new Date('2025-05-01'),
    registrationCity: 'Jubail',
    capacity: 60,
    grossVehicleWeight: 70000,
    netWeight: 20000,
    numberOfAxles: 8,
    lengthMeters: 22.0,
    widthMeters: 3.0,
    heightMeters: 4.2,
    fuelType: 'DIESEL',
    tankCapacityLiters: 600,
    engineCapacityCC: 16100,
    transmissionType: 'Automatic',
    horsePower: 750,
    tgaOperationCardNumber: 'TGA-OC-2020-0007',
    tgaOperationCardExpiry: new Date('2025-03-01'),
    waselTrackerId: 'WASEL-SAT-006',
    waselConnected: true,
    speedLimiterInstalled: true,
    speedLimitKmh: 80,
    insuranceProvider: 'Tawuniya',
    insurancePolicyNo: 'TWN-2024-HV-0099',
    insuranceType: 'COMPREHENSIVE',
    insuranceStartDate: new Date('2024-01-01'),
    insuranceExpiryDate: new Date('2025-01-01'),
    lastMvpiDate: new Date('2024-05-01'),
    nextMvpiDate: new Date('2025-05-01'),
    mvpiStation: 'Fahes Jubail',
    mvpiResult: 'PASS',
    currentOdometerKm: 312000,
    notes: 'Heavy equipment hauler. Industrial zone deliveries.',
  },
  {
    fleetNumber: 'VH-007',
    make: 'Hyundai',
    model: 'HD78',
    year: 2023,
    color: 'White',
    vehicleType: 'FLATBED',
    licensePlate: 'ي أ ب 6789',
    istimaraNumber: 'IST-2023-99001',
    istimaraExpiry: new Date('2025-11-15'),
    registrationCity: 'Riyadh',
    capacity: 5,
    grossVehicleWeight: 7500,
    netWeight: 3500,
    numberOfAxles: 2,
    fuelType: 'DIESEL',
    tankCapacityLiters: 150,
    transmissionType: 'Manual',
    horsePower: 150,
    waselTrackerId: 'WASEL-SAT-007',
    waselConnected: true,
    speedLimiterInstalled: true,
    speedLimitKmh: 100,
    insuranceProvider: 'Al Rajhi Takaful',
    insurancePolicyNo: 'ART-2024-FL-0112',
    insuranceType: 'AGAINST_OTHERS',
    insuranceStartDate: new Date('2024-11-01'),
    insuranceExpiryDate: new Date('2025-11-01'),
    currentOdometerKm: 41200,
    notes: 'Building materials distribution.',
  },
  {
    fleetNumber: 'VH-008',
    make: 'Mercedes-Benz',
    model: 'Sprinter 516 CDI',
    year: 2024,
    color: 'White',
    vehicleType: 'VAN',
    licensePlate: 'ت ث ج 1357',
    istimaraNumber: 'IST-2024-22334',
    istimaraExpiry: new Date('2026-09-01'),
    registrationCity: 'Riyadh',
    capacity: 2.5,
    grossVehicleWeight: 5500,
    netWeight: 3000,
    numberOfAxles: 2,
    fuelType: 'DIESEL',
    tankCapacityLiters: 75,
    transmissionType: 'Automatic',
    horsePower: 163,
    waselConnected: false,
    speedLimiterInstalled: false,
    insuranceProvider: 'Walaa Insurance',
    insurancePolicyNo: 'WAL-2024-VN-0044',
    insuranceType: 'THIRD_PARTY',
    insuranceStartDate: new Date('2024-09-01'),
    insuranceExpiryDate: new Date('2025-09-01'),
    currentOdometerKm: 5200,
    notes: 'Last-mile delivery van — e-commerce fulfillment.',
  },
  {
    fleetNumber: 'VH-009',
    make: 'DAF',
    model: 'XF 530 FTG',
    year: 2022,
    color: 'Orange',
    vehicleType: 'RIGID_TRUCK',
    licensePlate: 'خ د ذ 2468',
    chassisNumber: 'XLRTE47MS0G098765',
    istimaraNumber: 'IST-2022-66778',
    istimaraExpiry: new Date('2024-12-01'),
    registrationCity: 'Riyadh',
    capacity: 15,
    grossVehicleWeight: 26000,
    netWeight: 11000,
    numberOfAxles: 3,
    lengthMeters: 10.0,
    widthMeters: 2.55,
    heightMeters: 3.6,
    fuelType: 'DIESEL',
    tankCapacityLiters: 350,
    engineCapacityCC: 12900,
    transmissionType: 'Automatic',
    horsePower: 530,
    tgaOperationCardNumber: 'TGA-OC-2022-0033',
    tgaOperationCardExpiry: new Date('2024-11-01'),
    waselTrackerId: 'WASEL-SAT-009',
    waselConnected: true,
    speedLimiterInstalled: true,
    speedLimitKmh: 100,
    insuranceProvider: 'Tawuniya',
    insurancePolicyNo: 'TWN-2023-FL-0155',
    insuranceType: 'COMPREHENSIVE',
    insuranceStartDate: new Date('2023-12-01'),
    insuranceExpiryDate: new Date('2024-12-01'),
    lastMvpiDate: new Date('2024-01-15'),
    nextMvpiDate: new Date('2025-01-15'),
    mvpiStation: 'Fahes Riyadh - South',
    mvpiResult: 'PASS',
    currentOdometerKm: 145600,
    status: 'IN_MAINTENANCE',
    notes: 'Engine overhaul in progress — expected return mid-Oct.',
  },
  {
    fleetNumber: 'VH-010',
    make: 'Scania',
    model: 'R 500 A6x2',
    year: 2023,
    color: 'Green',
    vehicleType: 'ARTICULATED_TRUCK',
    licensePlate: 'ز س ص 3690',
    chassisNumber: 'XLER500A6X2N445566',
    istimaraNumber: 'IST-2023-88990',
    istimaraExpiry: new Date('2025-10-01'),
    registrationCity: 'Riyadh',
    capacity: 28,
    grossVehicleWeight: 48000,
    netWeight: 20000,
    numberOfAxles: 6,
    lengthMeters: 18.0,
    widthMeters: 2.55,
    heightMeters: 4.0,
    fuelType: 'DIESEL',
    tankCapacityLiters: 450,
    engineCapacityCC: 12700,
    transmissionType: 'Automatic',
    horsePower: 500,
    tgaOperationCardNumber: 'TGA-OC-2023-0101',
    tgaOperationCardExpiry: new Date('2025-12-01'),
    waselTrackerId: 'WASEL-SAT-010',
    waselConnected: true,
    speedLimiterInstalled: true,
    speedLimitKmh: 90,
    insuranceProvider: 'Tawuniya',
    insurancePolicyNo: 'TWN-2024-FL-0200',
    insuranceType: 'COMPREHENSIVE',
    insuranceStartDate: new Date('2024-10-01'),
    insuranceExpiryDate: new Date('2025-10-01'),
    lastMvpiDate: new Date('2024-10-01'),
    nextMvpiDate: new Date('2025-10-01'),
    mvpiStation: 'Fahes Riyadh - Al Sulay',
    mvpiResult: 'PASS',
    currentOdometerKm: 67800,
    notes: 'Cross-country logistics — Riyadh ↔ Dammam ↔ Jubail.',
  },
];

async function seedVehicles() {
  console.log('🚛 Seeding vehicle categories...');

  // Upsert default categories
  for (const cat of DEFAULT_CATEGORIES) {
    await prisma.vehicleCategory.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, description: cat.description, icon: cat.icon, isDefault: true },
      create: { ...cat, isDefault: true },
    });
  }
  console.log(`   ✓ ${DEFAULT_CATEGORIES.length} categories seeded`);

  // Seed vehicles
  console.log('🚛 Seeding sample vehicles...');
  for (const v of SAMPLE_VEHICLES) {
    const existing = await prisma.vehicle.findUnique({ where: { fleetNumber: v.fleetNumber } });
    if (!existing) {
      await prisma.vehicle.create({ data: v as any });
      console.log(`   ✓ ${v.fleetNumber} — ${v.make} ${v.model}`);
    } else {
      console.log(`   ○ ${v.fleetNumber} already exists, skipping`);
    }
  }

  console.log('\n✅ Vehicle seeding complete!');
}

seedVehicles()
  .catch((e) => {
    console.error('Seeding failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
