import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const DEFAULT_CATEGORIES = [
  { slug: 'RIGID_TRUCK', name: 'Rigid Truck', description: 'Rigid body truck for general freight', icon: '🚛' },
  { slug: 'ARTICULATED_TRUCK', name: 'Articulated Truck', description: 'Tractor + trailer combination', icon: '🚜' },
  { slug: 'TANKER', name: 'Tanker', description: 'Liquid/gas transport tanker', icon: '🛢' },
  { slug: 'REFRIGERATED', name: 'Refrigerated', description: 'Temperature-controlled reefer truck', icon: '❄️' },
  { slug: 'FLATBED', name: 'Flatbed', description: 'Open flatbed for oversized cargo', icon: '📏' },
  { slug: 'BOX_TRUCK', name: 'Box Truck', description: 'Enclosed box body truck', icon: '📦' },
  { slug: 'PICKUP', name: 'Pickup', description: 'Light commercial pickup truck', icon: '🛻' },
  { slug: 'VAN', name: 'Van', description: 'Delivery van for last-mile', icon: '🚐' },
  { slug: 'TRAILER', name: 'Trailer', description: 'Standalone trailer unit', icon: '🔗' },
  { slug: 'LOWBED', name: 'Lowbed', description: 'Heavy equipment hauler / lowloader', icon: '⚙️' },
  { slug: 'CURTAIN_SIDER', name: 'Curtain Sider', description: 'Side-curtain truck for easy loading', icon: '🏗' },
  { slug: 'CAR_CARRIER', name: 'Car Carrier', description: 'Multi-level vehicle transporter', icon: '🚗' },
  { slug: 'TIPPER', name: 'Tipper/Dump Truck', description: 'Hydraulic tipping body for bulk materials', icon: '🪨' },
  { slug: 'CEMENT_MIXER', name: 'Cement Mixer', description: 'Rotating drum concrete mixer', icon: '🏗' },
  { slug: 'CRANE_TRUCK', name: 'Crane Truck', description: 'Truck-mounted crane for heavy lifts', icon: '🏗' },
];

async function seedAll() {
  console.log('🚀 Starting full database migration and seed...\n');

  // 1. Seed Users
  console.log('👥 Seeding Users...');
  const adminPassword = await bcrypt.hash('admin123', 10);
  const driverPassword = await bcrypt.hash('driver123', 10);
  const customerPassword = await bcrypt.hash('customer123', 10);

  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@mmt.com' },
    update: { password: adminPassword, role: 'ADMIN' },
    create: { email: 'admin@mmt.com', password: adminPassword, role: 'ADMIN' },
  });

  const driverUser = await prisma.user.upsert({
    where: { email: 'driver@mmt.com' },
    update: { password: driverPassword, role: 'DRIVER' },
    create: { email: 'driver@mmt.com', password: driverPassword, role: 'DRIVER' },
  });

  const customerUser = await prisma.user.upsert({
    where: { email: 'customer@mmt.com' },
    update: { password: customerPassword, role: 'CUSTOMER' },
    create: { email: 'customer@mmt.com', password: customerPassword, role: 'CUSTOMER' },
  });

  // Also support admin@mmtlogistics.com
  await prisma.user.upsert({
    where: { email: 'admin@mmtlogistics.com' },
    update: { password: adminPassword, role: 'ADMIN' },
    create: { email: 'admin@mmtlogistics.com', password: adminPassword, role: 'ADMIN' },
  });
  console.log('   ✓ Admin (admin@mmt.com / admin123)');
  console.log('   ✓ Driver (driver@mmt.com / driver123)');
  console.log('   ✓ Customer (customer@mmt.com / customer123)');

  // 2. Seed Vehicle Categories
  console.log('\n🏷️  Seeding Vehicle Categories...');
  for (const cat of DEFAULT_CATEGORIES) {
    await prisma.vehicleCategory.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, description: cat.description, icon: cat.icon, isDefault: true },
      create: { ...cat, isDefault: true },
    });
  }
  console.log(`   ✓ ${DEFAULT_CATEGORIES.length} categories seeded`);

  // 3. Seed Drivers
  console.log('\n🪪 Seeding Drivers...');
  const driversData = [
    {
      employeeId: 'DRV-001',
      firstName: 'Mohammed',
      lastName: 'Al-Qahtani',
      dateOfBirth: new Date('1988-03-15'),
      gender: 'MALE' as const,
      bloodGroup: 'O_POS' as const,
      nationality: 'Saudi',
      residencyType: 'SAUDI_NATIONAL' as const,
      nationalIdNumber: '1089456723',
      phone: '+966 55 123 4567',
      currentAddress: 'Al Malaz District, Building 12, Apt 4',
      city: 'Riyadh',
      region: 'Riyadh Region',
      postalCode: '12631',
      emergencyContactName: 'Ahmed Al-Qahtani',
      emergencyContactPhone: '+966 55 987 6543',
      emergencyContactRelation: 'Brother',
      dateOfJoining: new Date('2022-01-10'),
      employmentType: 'FULL_TIME' as const,
      status: 'ACTIVE' as const,
      department: 'Long Haul',
      salary: 5500,
      bankName: 'Al Rajhi Bank',
      ibanNumber: 'SA4420000001234567891234',
      gosiNumber: 'GOSI-98765',
      licenseNumber: 'SA-DL-29834756',
      licenseType: 'HEAVY_EQUIPMENT' as const,
      licenseIssuingAuthority: 'Riyadh Muroor',
      licenseIssueDate: new Date('2020-06-01'),
      licenseExpiryDate: new Date('2027-06-01'),
      hazmatCertified: true,
      defensiveDrivingCert: true,
      waselRegistrationNumber: 'WSL-445566',
      tgaCardNumber: 'TGA-112233',
      tgaCardExpiry: new Date('2026-12-31'),
      medicalFitness: 'FIT' as const,
      medicalCertExpiry: new Date('2027-03-15'),
      drugTestDate: new Date('2026-08-01'),
      drugTestResult: 'VERIFIED' as const,
      backgroundCheckStatus: 'VERIFIED' as const,
      backgroundCheckDate: new Date('2022-01-05'),
      saudiPoliceCheck: 'VERIFIED' as const,
      saudiPoliceCheckDate: new Date('2022-01-03'),
      homeCountryClearance: 'VERIFIED' as const,
      notes: 'Senior driver. Excellent track record. Primary driver for Actros VH-001.',
    },
    {
      employeeId: 'DRV-002',
      firstName: 'Rajesh',
      lastName: 'Kumar',
      dateOfBirth: new Date('1992-07-22'),
      gender: 'MALE' as const,
      bloodGroup: 'B_POS' as const,
      nationality: 'Indian',
      residencyType: 'IQAMA_HOLDER' as const,
      iqamaNumber: '2398765432',
      iqamaExpiryDate: new Date('2026-11-15'),
      sponsorName: 'MMT Logistics Co.',
      borderNumber: 'BN-778899',
      passportNumber: 'T4567890',
      passportIssuingCountry: 'India',
      passportIssueDate: new Date('2021-04-10'),
      passportExpiryDate: new Date('2031-04-09'),
      visaType: 'WORK_VISA' as const,
      visaExpiryDate: new Date('2026-11-15'),
      phone: '+966 50 234 5678',
      alternatePhone: '+91 98765 43210',
      email: 'rajesh.k@email.com',
      currentAddress: 'Al Batha, Worker Housing Block C, Room 12',
      permanentAddress: 'Village Rampur, District Lucknow, UP, India',
      city: 'Riyadh',
      region: 'Riyadh Region',
      postalCode: '11564',
      emergencyContactName: 'Sunita Kumar',
      emergencyContactPhone: '+91 98765 12345',
      emergencyContactRelation: 'Spouse',
      dateOfJoining: new Date('2023-06-15'),
      employmentType: 'FULL_TIME' as const,
      status: 'ON_LEAVE' as const, // Currently on approved leave!
      department: 'Cold Chain',
      salary: 3800,
      bankName: 'Alinma Bank',
      ibanNumber: 'SA0580000001234567890123',
      gosiNumber: 'GOSI-54321',
      licenseNumber: 'SA-DL-10293847',
      licenseType: 'HEAVY_EQUIPMENT' as const,
      licenseIssuingAuthority: 'Riyadh Muroor',
      licenseIssueDate: new Date('2023-07-01'),
      licenseExpiryDate: new Date('2026-10-05'),
      hazmatCertified: false,
      defensiveDrivingCert: true,
      medicalFitness: 'FIT' as const,
      medicalCertExpiry: new Date('2027-06-15'),
      drugTestDate: new Date('2026-07-20'),
      drugTestResult: 'VERIFIED' as const,
      backgroundCheckStatus: 'VERIFIED' as const,
      saudiPoliceCheck: 'VERIFIED' as const,
      saudiPoliceCheckDate: new Date('2023-06-10'),
      homeCountryClearance: 'VERIFIED' as const,
      notes: 'Assigned to Reefer VH-004. Currently on annual leave to India (returns next week).',
    },
    {
      employeeId: 'DRV-003',
      firstName: 'Abdul',
      lastName: 'Rahman',
      dateOfBirth: new Date('1995-11-03'),
      gender: 'MALE' as const,
      bloodGroup: 'A_POS' as const,
      nationality: 'Pakistani',
      residencyType: 'IQAMA_HOLDER' as const,
      iqamaNumber: '2456789012',
      iqamaExpiryDate: new Date('2026-09-28'),
      sponsorName: 'MMT Logistics Co.',
      passportNumber: 'AB1234567',
      passportIssuingCountry: 'Pakistan',
      passportIssueDate: new Date('2020-08-15'),
      passportExpiryDate: new Date('2030-08-14'),
      visaType: 'WORK_VISA' as const,
      visaExpiryDate: new Date('2026-09-28'),
      phone: '+966 53 345 6789',
      alternatePhone: '+92 300 1234567',
      currentAddress: 'Industrial Area 2, Camp 5, Room 8',
      city: 'Dammam',
      region: 'Eastern Province',
      postalCode: '31411',
      emergencyContactName: 'Fatima Rahman',
      emergencyContactPhone: '+92 300 7654321',
      emergencyContactRelation: 'Mother',
      dateOfJoining: new Date('2024-02-01'),
      employmentType: 'CONTRACT' as const,
      status: 'ACTIVE' as const,
      department: 'Fuel Logistics',
      salary: 4000,
      bankName: 'Saudi National Bank (SNB)',
      ibanNumber: 'SA1010000001234567890987',
      licenseNumber: 'SA-DL-56473829',
      licenseType: 'PUBLIC_HEAVY' as const,
      licenseIssuingAuthority: 'Dammam Muroor',
      licenseIssueDate: new Date('2024-02-15'),
      licenseExpiryDate: new Date('2026-09-25'),
      hazmatCertified: true,
      defensiveDrivingCert: true,
      medicalFitness: 'FIT' as const,
      medicalCertExpiry: new Date('2026-10-01'),
      drugTestDate: new Date('2026-08-15'),
      drugTestResult: 'VERIFIED' as const,
      backgroundCheckStatus: 'VERIFIED' as const,
      saudiPoliceCheck: 'VERIFIED' as const,
      homeCountryClearance: 'PENDING' as const,
      saherViolations: 1,
      notes: 'Assigned to Tanker VH-003. Certified for fuel and hazmat transport.',
    },
    {
      employeeId: 'DRV-004',
      firstName: 'Tariq',
      lastName: 'Mansour',
      dateOfBirth: new Date('1990-05-18'),
      gender: 'MALE' as const,
      bloodGroup: 'AB_POS' as const,
      nationality: 'Saudi',
      residencyType: 'SAUDI_NATIONAL' as const,
      nationalIdNumber: '1076543219',
      phone: '+966 54 876 5432',
      currentAddress: 'Al Hamra, Jeddah',
      city: 'Jeddah',
      region: 'Makkah Region',
      postalCode: '21514',
      emergencyContactName: 'Khalid Mansour',
      emergencyContactPhone: '+966 54 111 2233',
      emergencyContactRelation: 'Father',
      dateOfJoining: new Date('2023-01-15'),
      employmentType: 'FULL_TIME' as const,
      status: 'ACTIVE' as const,
      department: 'Distribution',
      salary: 5000,
      bankName: 'Al Rajhi Bank',
      ibanNumber: 'SA4420000009876543210123',
      licenseNumber: 'SA-DL-87654321',
      licenseType: 'HEAVY_EQUIPMENT' as const,
      licenseIssuingAuthority: 'Jeddah Muroor',
      licenseIssueDate: new Date('2021-03-10'),
      licenseExpiryDate: new Date('2027-03-10'),
      hazmatCertified: false,
      defensiveDrivingCert: true,
      medicalFitness: 'FIT' as const,
      medicalCertExpiry: new Date('2027-02-15'),
      drugTestDate: new Date('2026-06-10'),
      drugTestResult: 'VERIFIED' as const,
      backgroundCheckStatus: 'VERIFIED' as const,
      saudiPoliceCheck: 'VERIFIED' as const,
      notes: 'Assigned to Rigid Truck VH-002. Western region distribution routes.',
    },
  ];

  const seededDrivers: Record<string, string> = {};
  for (const d of driversData) {
    const existing = await prisma.driver.findUnique({ where: { employeeId: d.employeeId } });
    if (existing) {
      const updated = await prisma.driver.update({ where: { employeeId: d.employeeId }, data: d });
      seededDrivers[d.employeeId] = updated.id;
      console.log(`   ✓ Updated ${d.firstName} ${d.lastName} (${d.employeeId})`);
    } else {
      const created = await prisma.driver.create({ data: d });
      seededDrivers[d.employeeId] = created.id;
      console.log(`   ✓ Created ${d.firstName} ${d.lastName} (${d.employeeId})`);
    }
  }

  // 4. Seed Driver Leaves (Rajesh Kumar is on leave)
  console.log('\n🏖️  Seeding Driver Leaves...');
  const rajeshId = seededDrivers['DRV-002'];
  if (rajeshId) {
    const today = new Date();
    const leaveStart = new Date(today);
    leaveStart.setDate(today.getDate() - 10);
    const leaveEnd = new Date(today);
    leaveEnd.setDate(today.getDate() + 10);

    const existingLeave = await prisma.driverLeave.findFirst({
      where: { driverId: rajeshId, status: 'APPROVED' },
    });
    if (!existingLeave) {
      await prisma.driverLeave.create({
        data: {
          driverId: rajeshId,
          startDate: leaveStart,
          endDate: leaveEnd,
          reason: 'Annual Home Leave (India) - Approved vacation',
          status: 'APPROVED',
        },
      });
      console.log('   ✓ Added active approved leave for Rajesh Kumar (DRV-002)');
    }
  }

  // 5. Seed Vehicles with assigned drivers
  console.log('\n🚛 Seeding Vehicles & Driver Assignments...');
  const vehiclesData = [
    {
      fleetNumber: 'VH-001',
      make: 'Mercedes-Benz',
      model: 'Actros 2645',
      year: 2023,
      color: 'White',
      vehicleType: 'ARTICULATED_TRUCK',
      licensePlate: 'أ ب ت 1234',
      chassisNumber: 'WDB9634031L654321',
      engineNumber: 'OM471-A6-001',
      istimaraNumber: 'IST-2023-98765',
      istimaraExpiry: new Date('2025-06-15'),
      registrationCity: 'Riyadh',
      capacity: 26,
      grossVehicleWeight: 45000,
      netWeight: 19000,
      numberOfAxles: 6,
      lengthMeters: 16.5,
      widthMeters: 2.55,
      heightMeters: 4.0,
      fuelType: 'DIESEL' as const,
      tankCapacityLiters: 400,
      engineCapacityCC: 12800,
      transmissionType: 'Automatic',
      horsePower: 450,
      tgaOperationCardNumber: 'TGA-OC-2023-0012',
      tgaOperationCardExpiry: new Date('2025-04-20'),
      waselTrackerId: 'WASEL-SAT-001',
      waselConnected: true,
      speedLimiterInstalled: true,
      speedLimitKmh: 90,
      insuranceProvider: 'Tawuniya',
      insurancePolicyNo: 'TWN-2024-FL-0012',
      insuranceType: 'COMPREHENSIVE' as const,
      insuranceStartDate: new Date('2024-01-01'),
      insuranceExpiryDate: new Date('2025-01-01'),
      lastMvpiDate: new Date('2024-09-01'),
      nextMvpiDate: new Date('2025-09-01'),
      mvpiStation: 'Fahes Riyadh - Al Rimal',
      mvpiResult: 'PASS',
      currentOdometerKm: 84320,
      assignedDriverId: seededDrivers['DRV-001'] || null, // Mohammed Al-Qahtani
      notes: 'Flagship long-haul truck. Assigned to Mohammed Al-Qahtani (Active).',
    },
    {
      fleetNumber: 'VH-002',
      make: 'Isuzu',
      model: 'FVR 34',
      year: 2022,
      color: 'White',
      vehicleType: 'RIGID_TRUCK',
      licensePlate: 'س ص ع 5678',
      chassisNumber: 'JALFVR34E71002345',
      engineNumber: '6HK1-TC-9821',
      istimaraNumber: 'IST-2022-44321',
      istimaraExpiry: new Date('2025-03-10'),
      registrationCity: 'Jeddah',
      capacity: 10,
      grossVehicleWeight: 18000,
      netWeight: 8000,
      numberOfAxles: 2,
      lengthMeters: 8.8,
      widthMeters: 2.45,
      heightMeters: 3.2,
      fuelType: 'DIESEL' as const,
      tankCapacityLiters: 200,
      engineCapacityCC: 7800,
      transmissionType: 'Manual',
      horsePower: 260,
      tgaOperationCardNumber: 'TGA-OC-2022-0089',
      tgaOperationCardExpiry: new Date('2025-08-15'),
      waselTrackerId: 'WASEL-SAT-002',
      waselConnected: true,
      speedLimiterInstalled: true,
      speedLimitKmh: 90,
      insuranceProvider: 'Al Rajhi Takaful',
      insurancePolicyNo: 'ART-2024-V-9921',
      insuranceType: 'COMPREHENSIVE' as const,
      insuranceStartDate: new Date('2024-03-01'),
      insuranceExpiryDate: new Date('2025-03-01'),
      lastMvpiDate: new Date('2024-08-15'),
      nextMvpiDate: new Date('2025-08-15'),
      mvpiStation: 'Fahes Jeddah - Kilo 14',
      mvpiResult: 'PASS',
      currentOdometerKm: 112450,
      assignedDriverId: seededDrivers['DRV-004'] || null, // Tariq Mansour
      notes: 'Urban distribution in Jeddah & Makkah. Assigned to Tariq Mansour (Active).',
    },
    {
      fleetNumber: 'VH-003',
      make: 'MAN',
      model: 'TGS 33.400',
      year: 2021,
      color: 'Silver',
      vehicleType: 'TANKER',
      licensePlate: 'د ذ ر 9012',
      chassisNumber: 'WMA03ZZZ7MP123456',
      engineNumber: 'D2066-LF-0091',
      istimaraNumber: 'IST-2021-11223',
      istimaraExpiry: new Date('2025-01-30'),
      registrationCity: 'Dammam',
      capacity: 32,
      grossVehicleWeight: 44000,
      netWeight: 12000,
      numberOfAxles: 4,
      lengthMeters: 14.2,
      widthMeters: 2.5,
      heightMeters: 3.8,
      fuelType: 'DIESEL' as const,
      tankCapacityLiters: 500,
      engineCapacityCC: 10500,
      transmissionType: 'Automatic',
      horsePower: 400,
      tgaOperationCardNumber: 'TGA-OC-2021-0145',
      tgaOperationCardExpiry: new Date('2025-02-15'),
      waselTrackerId: 'WASEL-SAT-003',
      waselConnected: true,
      speedLimiterInstalled: true,
      speedLimitKmh: 80,
      insuranceProvider: 'Bupa Arabia',
      insurancePolicyNo: 'BPA-2024-TK-0044',
      insuranceType: 'COMPREHENSIVE' as const,
      insuranceStartDate: new Date('2024-02-01'),
      insuranceExpiryDate: new Date('2025-02-01'),
      lastMvpiDate: new Date('2024-07-20'),
      nextMvpiDate: new Date('2025-07-20'),
      mvpiStation: 'Fahes Dammam - Al Khobar Rd',
      mvpiResult: 'PASS',
      currentOdometerKm: 145800,
      assignedDriverId: seededDrivers['DRV-003'] || null, // Abdul Rahman
      notes: 'Liquid fuel transport. Assigned to Abdul Rahman (Hazmat certified).',
    },
    {
      fleetNumber: 'VH-004',
      make: 'Volvo',
      model: 'FH 460 Reefer',
      year: 2023,
      color: 'Blue',
      vehicleType: 'REFRIGERATED',
      licensePlate: 'ط ظ ع 3456',
      chassisNumber: 'YV2RT40A7PB987654',
      engineNumber: 'D13K460-EU6-443',
      istimaraNumber: 'IST-2023-77654',
      istimaraExpiry: new Date('2025-11-20'),
      registrationCity: 'Riyadh',
      capacity: 22,
      grossVehicleWeight: 40000,
      netWeight: 18000,
      numberOfAxles: 5,
      lengthMeters: 15.0,
      widthMeters: 2.6,
      heightMeters: 4.1,
      fuelType: 'DIESEL' as const,
      tankCapacityLiters: 450,
      engineCapacityCC: 12800,
      transmissionType: 'Automatic',
      horsePower: 460,
      tgaOperationCardNumber: 'TGA-OC-2023-0077',
      tgaOperationCardExpiry: new Date('2025-10-15'),
      waselTrackerId: 'WASEL-SAT-004',
      waselConnected: true,
      speedLimiterInstalled: true,
      speedLimitKmh: 90,
      insuranceProvider: 'Tawuniya',
      insurancePolicyNo: 'TWN-2024-RF-0088',
      insuranceType: 'COMPREHENSIVE' as const,
      insuranceStartDate: new Date('2024-05-01'),
      insuranceExpiryDate: new Date('2025-05-01'),
      lastMvpiDate: new Date('2024-06-10'),
      nextMvpiDate: new Date('2025-06-10'),
      mvpiStation: 'Fahes Riyadh - Al Sulay',
      mvpiResult: 'PASS',
      currentOdometerKm: 52100,
      assignedDriverId: seededDrivers['DRV-002'] || null, // Rajesh Kumar (ON LEAVE)
      notes: 'Cold chain transport (-25°C to +15°C). Assigned to Rajesh Kumar (⚠️ ON LEAVE - temporary relief driver needed).',
    },
    {
      fleetNumber: 'VH-005',
      make: 'Scania',
      model: 'R 500 Flatbed',
      year: 2022,
      color: 'White',
      vehicleType: 'FLATBED',
      licensePlate: 'ف ق ك 7890',
      chassisNumber: 'YS2R4X20005678901',
      engineNumber: 'DC13-146-500',
      istimaraNumber: 'IST-2022-88990',
      istimaraExpiry: new Date('2025-05-18'),
      registrationCity: 'Jubail',
      capacity: 30,
      grossVehicleWeight: 48000,
      netWeight: 18000,
      numberOfAxles: 6,
      lengthMeters: 17.0,
      widthMeters: 2.55,
      heightMeters: 3.5,
      fuelType: 'DIESEL' as const,
      tankCapacityLiters: 400,
      engineCapacityCC: 13000,
      transmissionType: 'Automatic',
      horsePower: 500,
      tgaOperationCardNumber: 'TGA-OC-2022-0211',
      tgaOperationCardExpiry: new Date('2025-06-01'),
      waselTrackerId: 'WASEL-SAT-005',
      waselConnected: true,
      speedLimiterInstalled: true,
      speedLimitKmh: 90,
      insuranceProvider: 'Al Sagr Insurance',
      insurancePolicyNo: 'ASI-2024-FB-0120',
      insuranceType: 'COMPREHENSIVE' as const,
      insuranceStartDate: new Date('2024-04-01'),
      insuranceExpiryDate: new Date('2025-04-01'),
      lastMvpiDate: new Date('2024-05-22'),
      nextMvpiDate: new Date('2025-05-22'),
      mvpiStation: 'Fahes Dammam - Jubail Highway',
      mvpiResult: 'PASS',
      currentOdometerKm: 98400,
      notes: 'Heavy structural steel and pipe hauling for Jubail industrial zone.',
    },
    {
      fleetNumber: 'VH-006',
      make: 'Hino',
      model: '500 Series Box',
      year: 2020,
      color: 'White',
      vehicleType: 'BOX_TRUCK',
      licensePlate: 'ل م ن 2345',
      chassisNumber: 'JHDFE1JPA00123890',
      engineNumber: 'J08E-WD-5512',
      istimaraNumber: 'IST-2020-55443',
      istimaraExpiry: new Date('2024-12-15'),
      registrationCity: 'Riyadh',
      capacity: 8,
      grossVehicleWeight: 15000,
      netWeight: 7000,
      numberOfAxles: 2,
      lengthMeters: 7.5,
      widthMeters: 2.4,
      heightMeters: 3.4,
      fuelType: 'DIESEL' as const,
      tankCapacityLiters: 200,
      engineCapacityCC: 7700,
      transmissionType: 'Manual',
      horsePower: 240,
      tgaOperationCardNumber: 'TGA-OC-2020-0988',
      tgaOperationCardExpiry: new Date('2024-11-30'),
      waselTrackerId: 'WASEL-SAT-006',
      waselConnected: false,
      speedLimiterInstalled: true,
      speedLimitKmh: 90,
      insuranceProvider: 'Wafa Insurance',
      insurancePolicyNo: 'WFA-2024-BX-0033',
      insuranceType: 'THIRD_PARTY' as const,
      insuranceStartDate: new Date('2024-01-15'),
      insuranceExpiryDate: new Date('2025-01-15'),
      lastMvpiDate: new Date('2023-11-10'),
      nextMvpiDate: new Date('2024-11-10'),
      mvpiStation: 'Fahes Riyadh - Al Sulay',
      mvpiResult: 'PASS',
      currentOdometerKm: 187600,
      notes: '⚠️ Needs renewal: Istimara, TGA, and MVPI expiring soon.',
    },
    {
      fleetNumber: 'VH-007',
      make: 'Toyota',
      model: 'Hilux Double Cab',
      year: 2024,
      color: 'White',
      vehicleType: 'PICKUP',
      licensePlate: 'هـ و ي 6789',
      chassisNumber: 'MR0BA3CD400554433',
      engineNumber: '1GD-FTV-8821',
      istimaraNumber: 'IST-2024-10293',
      istimaraExpiry: new Date('2027-01-10'),
      registrationCity: 'Riyadh',
      capacity: 1.2,
      grossVehicleWeight: 3150,
      netWeight: 1950,
      numberOfAxles: 2,
      lengthMeters: 5.3,
      widthMeters: 1.85,
      heightMeters: 1.81,
      fuelType: 'DIESEL' as const,
      tankCapacityLiters: 80,
      engineCapacityCC: 2800,
      transmissionType: 'Automatic',
      horsePower: 201,
      speedLimiterInstalled: false,
      speedLimitKmh: 120,
      insuranceProvider: 'Tawuniya',
      insurancePolicyNo: 'TWN-2024-PU-0331',
      insuranceType: 'COMPREHENSIVE' as const,
      insuranceStartDate: new Date('2024-01-10'),
      insuranceExpiryDate: new Date('2025-01-10'),
      lastMvpiDate: new Date('2024-01-10'),
      nextMvpiDate: new Date('2027-01-10'),
      mvpiStation: 'Fahes Riyadh - Al Rimal',
      mvpiResult: 'PASS',
      currentOdometerKm: 18400,
      notes: 'Field supervision and express parts dispatch.',
    },
    {
      fleetNumber: 'VH-008',
      make: 'Ford',
      model: 'Transit 350L Van',
      year: 2023,
      color: 'Silver',
      vehicleType: 'VAN',
      licensePlate: 'أ ح خ 4567',
      chassisNumber: 'WF0XXXTTGXPK12987',
      engineNumber: 'YNF6-20098',
      istimaraNumber: 'IST-2023-33445',
      istimaraExpiry: new Date('2026-08-20'),
      registrationCity: 'Riyadh',
      capacity: 1.8,
      grossVehicleWeight: 3500,
      netWeight: 2200,
      numberOfAxles: 2,
      lengthMeters: 5.98,
      widthMeters: 2.06,
      heightMeters: 2.78,
      fuelType: 'DIESEL' as const,
      tankCapacityLiters: 80,
      engineCapacityCC: 2000,
      transmissionType: 'Automatic',
      horsePower: 170,
      tgaOperationCardNumber: 'TGA-OC-2023-0881',
      tgaOperationCardExpiry: new Date('2026-08-01'),
      waselTrackerId: 'WASEL-SAT-008',
      waselConnected: true,
      speedLimiterInstalled: true,
      speedLimitKmh: 100,
      insuranceProvider: 'Al Rajhi Takaful',
      insurancePolicyNo: 'ART-2024-VN-1100',
      insuranceType: 'COMPREHENSIVE' as const,
      insuranceStartDate: new Date('2024-08-01'),
      insuranceExpiryDate: new Date('2025-08-01'),
      lastMvpiDate: new Date('2024-08-10'),
      nextMvpiDate: new Date('2025-08-10'),
      mvpiStation: 'Fahes Riyadh - Al Rimal',
      mvpiResult: 'PASS',
      currentOdometerKm: 34200,
      notes: 'E-commerce parcel delivery across Greater Riyadh.',
    },
    {
      fleetNumber: 'VH-009',
      make: 'Goldhofer',
      model: 'STZ-VL 4 Lowbed',
      year: 2021,
      color: 'Yellow',
      vehicleType: 'LOWBED',
      licensePlate: 'ب ج د 8901',
      chassisNumber: 'WGOH0004XMA009876',
      istimaraNumber: 'IST-2021-99887',
      istimaraExpiry: new Date('2025-09-30'),
      registrationCity: 'Dammam',
      capacity: 55,
      grossVehicleWeight: 70000,
      netWeight: 15000,
      numberOfAxles: 4,
      lengthMeters: 19.5,
      widthMeters: 3.0,
      heightMeters: 1.2,
      fuelType: 'DIESEL' as const,
      tgaOperationCardNumber: 'TGA-OC-2021-0902',
      tgaOperationCardExpiry: new Date('2025-09-01'),
      insuranceProvider: 'Tawuniya',
      insurancePolicyNo: 'TWN-2024-LB-0055',
      insuranceType: 'COMPREHENSIVE' as const,
      insuranceStartDate: new Date('2024-09-01'),
      insuranceExpiryDate: new Date('2025-09-01'),
      lastMvpiDate: new Date('2024-09-15'),
      nextMvpiDate: new Date('2025-09-15'),
      mvpiStation: 'Fahes Dammam - Jubail Highway',
      mvpiResult: 'PASS',
      currentOdometerKm: 45000,
      notes: 'Heavy machinery transport (excavators, bulldozers, turbines). Requires MOT oversize permit.',
    },
    {
      fleetNumber: 'VH-010',
      make: 'Mercedes-Benz',
      model: 'Arocs 3345 Curtain Sider',
      year: 2023,
      color: 'White',
      vehicleType: 'CURTAIN_SIDER',
      licensePlate: 'ر ز س 2468',
      chassisNumber: 'WDB9640311K998877',
      engineNumber: 'OM471-B2-0099',
      istimaraNumber: 'IST-2023-12456',
      istimaraExpiry: new Date('2026-02-15'),
      registrationCity: 'Riyadh',
      capacity: 24,
      grossVehicleWeight: 42000,
      netWeight: 18000,
      numberOfAxles: 5,
      lengthMeters: 18.0,
      widthMeters: 2.55,
      heightMeters: 4.0,
      fuelType: 'DIESEL' as const,
      tankCapacityLiters: 450,
      engineCapacityCC: 12700,
      transmissionType: 'Automatic',
      horsePower: 500,
      tgaOperationCardNumber: 'TGA-OC-2023-0101',
      tgaOperationCardExpiry: new Date('2025-12-01'),
      waselTrackerId: 'WASEL-SAT-010',
      waselConnected: true,
      speedLimiterInstalled: true,
      speedLimitKmh: 90,
      insuranceProvider: 'Tawuniya',
      insurancePolicyNo: 'TWN-2024-FL-0200',
      insuranceType: 'COMPREHENSIVE' as const,
      insuranceStartDate: new Date('2024-10-01'),
      insuranceExpiryDate: new Date('2025-10-01'),
      lastMvpiDate: new Date('2024-10-01'),
      nextMvpiDate: new Date('2025-10-01'),
      mvpiStation: 'Fahes Riyadh - Al Sulay',
      mvpiResult: 'PASS',
      currentOdometerKm: 67800,
      notes: 'Cross-country logistics — Riyadh ↔ Dammam ↔ Jubail.',
    },
  ];

  for (const v of vehiclesData) {
    const existing = await prisma.vehicle.findUnique({ where: { fleetNumber: v.fleetNumber } });
    if (existing) {
      await prisma.vehicle.update({ where: { fleetNumber: v.fleetNumber }, data: v as any });
      console.log(`   ✓ Updated ${v.fleetNumber} (${v.make} ${v.model})`);
    } else {
      await prisma.vehicle.create({ data: v as any });
      console.log(`   ✓ Created ${v.fleetNumber} (${v.make} ${v.model})`);
    }
  }

  console.log('\n=========================================');
  console.log('✅ Full Migration & Seed Complete!');
  console.log('   Users: Admin, Driver, Customer');
  console.log(`   Categories: ${DEFAULT_CATEGORIES.length}`);
  console.log(`   Drivers: ${driversData.length}`);
  console.log(`   Vehicles: ${vehiclesData.length}`);
  console.log('   Driver-Vehicle assignments active!');
  console.log('=========================================\n');
}

seedAll()
  .catch((e) => {
    console.error('❌ Migration / Seed Error:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
