const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const drivers = [
    {
      employeeId: 'DRV-001',
      firstName: 'Mohammed',
      lastName: 'Al-Qahtani',
      dateOfBirth: new Date('1988-03-15'),
      gender: 'MALE',
      bloodGroup: 'O_POS',
      nationality: 'Saudi',
      residencyType: 'SAUDI_NATIONAL',
      nationalIdNumber: '1089456723',
      phone: '+966 55 123 4567',
      currentAddress: 'Al Malaz District, Building 12, Apt 4',
      city: 'Riyadh',
      region: 'Riyadh Region',
      postalCode: '12631',
      emergencyContactName: 'Ahmed Al-Qahtani',
      emergencyContactPhone: '+966 55 987 6543',
      emergencyContactRelation: 'Brother',
      dateOfJoining: new Date('2022-01-10'),
      employmentType: 'FULL_TIME',
      status: 'ACTIVE',
      department: 'Long Haul',
      salary: 5500,
      bankName: 'Al Rajhi Bank',
      ibanNumber: 'SA4420000001234567891234',
      gosiNumber: 'GOSI-98765',
      licenseNumber: 'SA-DL-29834756',
      licenseType: 'HEAVY_EQUIPMENT',
      licenseIssuingAuthority: 'Riyadh Muroor',
      licenseIssueDate: new Date('2020-06-01'),
      licenseExpiryDate: new Date('2027-06-01'),
      hazmatCertified: true,
      defensiveDrivingCert: true,
      waselRegistrationNumber: 'WSL-445566',
      tgaCardNumber: 'TGA-112233',
      tgaCardExpiry: new Date('2026-12-31'),
      medicalFitness: 'FIT',
      medicalCertExpiry: new Date('2027-03-15'),
      drugTestDate: new Date('2026-08-01'),
      drugTestResult: 'VERIFIED',
      backgroundCheckStatus: 'VERIFIED',
      backgroundCheckDate: new Date('2022-01-05'),
      saudiPoliceCheck: 'VERIFIED',
      saudiPoliceCheckDate: new Date('2022-01-03'),
      homeCountryClearance: 'VERIFIED',
      notes: 'Senior driver. Excellent track record. Hazmat routes certified.',
    },
    {
      employeeId: 'DRV-002',
      firstName: 'Rajesh',
      lastName: 'Kumar',
      dateOfBirth: new Date('1992-07-22'),
      gender: 'MALE',
      bloodGroup: 'B_POS',
      nationality: 'Indian',
      residencyType: 'IQAMA_HOLDER',
      iqamaNumber: '2398765432',
      iqamaExpiryDate: new Date('2026-11-15'),
      sponsorName: 'MMT Logistics Co.',
      borderNumber: 'BN-778899',
      passportNumber: 'T4567890',
      passportIssuingCountry: 'India',
      passportIssueDate: new Date('2021-04-10'),
      passportExpiryDate: new Date('2031-04-09'),
      visaType: 'WORK_VISA',
      visaExpiryDate: new Date('2026-11-15'),
      phone: '+966 50 234 5678',
      alternatePhone: '+91 98765 43210',
      email: 'rajesh.k@email.com',
      currentAddress: 'Al Batha, Worker Housing Block C, Room 12',
      permanentAddress: 'Village Rampur, District Lucknow, UP, India',
      city: 'Riyadh',
      region: 'Riyadh Region',
      postalCode: '11564',
      emergencyContactName: 'Sunita Kumar',
      emergencyContactPhone: '+91 98765 12345',
      emergencyContactRelation: 'Spouse',
      dateOfJoining: new Date('2023-06-15'),
      employmentType: 'FULL_TIME',
      status: 'ACTIVE',
      department: 'Last Mile',
      salary: 3500,
      bankName: 'Alinma Bank',
      ibanNumber: 'SA0580000001234567890123',
      gosiNumber: 'GOSI-54321',
      licenseNumber: 'SA-DL-10293847',
      licenseType: 'HEAVY_EQUIPMENT',
      licenseIssuingAuthority: 'Riyadh Muroor',
      licenseIssueDate: new Date('2023-07-01'),
      licenseExpiryDate: new Date('2026-10-05'),
      hazmatCertified: false,
      defensiveDrivingCert: true,
      medicalFitness: 'FIT',
      medicalCertExpiry: new Date('2027-06-15'),
      drugTestDate: new Date('2026-07-20'),
      drugTestResult: 'VERIFIED',
      backgroundCheckStatus: 'VERIFIED',
      saudiPoliceCheck: 'VERIFIED',
      saudiPoliceCheckDate: new Date('2023-06-10'),
      homeCountryClearance: 'VERIFIED',
      homeCountryClearanceDate: new Date('2023-05-20'),
    },
    {
      employeeId: 'DRV-003',
      firstName: 'Abdul',
      lastName: 'Rahman',
      dateOfBirth: new Date('1995-11-03'),
      gender: 'MALE',
      bloodGroup: 'A_POS',
      nationality: 'Pakistani',
      residencyType: 'IQAMA_HOLDER',
      iqamaNumber: '2456789012',
      iqamaExpiryDate: new Date('2026-09-28'),
      sponsorName: 'MMT Logistics Co.',
      passportNumber: 'AB1234567',
      passportIssuingCountry: 'Pakistan',
      passportIssueDate: new Date('2020-08-15'),
      passportExpiryDate: new Date('2030-08-14'),
      visaType: 'WORK_VISA',
      visaExpiryDate: new Date('2026-09-28'),
      phone: '+966 53 345 6789',
      alternatePhone: '+92 300 1234567',
      currentAddress: 'Industrial Area 2, Camp 5, Room 8',
      city: 'Dammam',
      region: 'Eastern Province',
      postalCode: '31411',
      emergencyContactName: 'Fatima Rahman',
      emergencyContactPhone: '+92 300 7654321',
      emergencyContactRelation: 'Mother',
      dateOfJoining: new Date('2024-02-01'),
      employmentType: 'CONTRACT',
      status: 'ACTIVE',
      department: 'Long Haul',
      salary: 3200,
      bankName: 'Saudi National Bank (SNB)',
      ibanNumber: 'SA1010000001234567890987',
      licenseNumber: 'SA-DL-56473829',
      licenseType: 'PUBLIC_HEAVY',
      licenseIssuingAuthority: 'Dammam Muroor',
      licenseIssueDate: new Date('2024-02-15'),
      licenseExpiryDate: new Date('2026-09-25'),
      medicalFitness: 'FIT',
      medicalCertExpiry: new Date('2026-10-01'),
      drugTestDate: new Date('2026-08-15'),
      drugTestResult: 'VERIFIED',
      backgroundCheckStatus: 'VERIFIED',
      saudiPoliceCheck: 'VERIFIED',
      homeCountryClearance: 'PENDING',
      saherViolations: 2,
      notes: 'License expiring soon. Renewal in progress.',
    },
  ];

  for (const driver of drivers) {
    await prisma.driver.create({ data: driver });
    console.log(`✓ Created ${driver.firstName} ${driver.lastName} (${driver.employeeId})`);
  }

  console.log('\nDone! 3 drivers seeded.');
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
